//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace HWCPipe {

public class HWCPipeAndroid {
  public static SWIGTYPE_p_std__unordered_mapT_std__string_hwcpipe__CpuCounter_t cpu_counter_names {
    get {
      SWIGTYPE_p_std__unordered_mapT_std__string_hwcpipe__CpuCounter_t ret = new SWIGTYPE_p_std__unordered_mapT_std__string_hwcpipe__CpuCounter_t(HWCPipeAndroidPINVOKE.cpu_counter_names_get(), true);
      return ret;
    } 
  }

  public static SWIGTYPE_p_std__unordered_mapT_hwcpipe__CpuCounter_hwcpipe__CpuCounterInfo_hwcpipe__CpuCounterHash_t cpu_counter_info {
    get {
      global::System.IntPtr cPtr = HWCPipeAndroidPINVOKE.cpu_counter_info_get();
      SWIGTYPE_p_std__unordered_mapT_hwcpipe__CpuCounter_hwcpipe__CpuCounterInfo_hwcpipe__CpuCounterHash_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__unordered_mapT_hwcpipe__CpuCounter_hwcpipe__CpuCounterInfo_hwcpipe__CpuCounterHash_t(cPtr, false);
      return ret;
    } 
  }

  public static SWIGTYPE_p_std__unordered_mapT_std__string_hwcpipe__GpuCounter_t gpu_counter_names {
    get {
      SWIGTYPE_p_std__unordered_mapT_std__string_hwcpipe__GpuCounter_t ret = new SWIGTYPE_p_std__unordered_mapT_std__string_hwcpipe__GpuCounter_t(HWCPipeAndroidPINVOKE.gpu_counter_names_get(), true);
      return ret;
    } 
  }

  public static SWIGTYPE_p_std__unordered_mapT_hwcpipe__GpuCounter_hwcpipe__GpuCounterInfo_hwcpipe__GpuCounterHash_t gpu_counter_info {
    get {
      global::System.IntPtr cPtr = HWCPipeAndroidPINVOKE.gpu_counter_info_get();
      SWIGTYPE_p_std__unordered_mapT_hwcpipe__GpuCounter_hwcpipe__GpuCounterInfo_hwcpipe__GpuCounterHash_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__unordered_mapT_hwcpipe__GpuCounter_hwcpipe__GpuCounterInfo_hwcpipe__GpuCounterHash_t(cPtr, false);
      return ret;
    } 
  }

}

}
